### ISSUE TITLE
Infinite loop in /admin page

### ISSUE THREAD

**Issue by souravnub** [souravnub/formless#19]
There is infinite loop in /admin page. It might have been caused by _chartData_ dependency in the useeffect in `[/src/components/ChartData.tsx ]`
<img width="952" alt="{5E7CED86-F350-4866-AAC6-63511F10E3C3}" src="https://github.com/user-attachments/assets/de5cf5bb-a1a0-4ca2-97d4-df2116cea48d">

**Comment by Chris-D259** [comment]
Fixed -  36 Requests will be made as there are 3 requests per month, 3*12 = 36 requests each time the chart is rendered
