### ISSUE TITLE
NA Checkbox Addition

### ISSUE THREAD

**Issue by Chris-D259** [souravnub/formless#27]
when creating a form, checkboxes should have some kind of option where you either type or select "N/A" since not all checkboxes on the forms are applicable to certain jobs

**Comment by souravnub** [comment]
<img width="374" alt="{87C2003B-051B-478A-876C-BDE8E6CAE6F7}" src="https://github.com/user-attachments/assets/b929f989-959b-41f7-b06e-067bc90e1339">
