### ISSUE TITLE
Report Text Headers and Formatting During Form Creation

### ISSUE THREAD

**Issue by Chris-D259** [souravnub/formless#29]
when creating a form, have an option where you can add headers/titles of sort within the form, for example you may have a title/header that says "Tasks to be Performed" and then its followed by 5 different text inputs labeled 1, 2, 3, 4, 5 (i will include an example form showing this) OR you can make it so adding a text input is similar to our current adding a checkbox in the way you supply a  title and then add multiple inputs from there (basically making it the same as adding a checkbox but for text input instead)

**Comment by souravnub** [comment]
DONE!
